### ISSUE TITLE
Allow plugins to manually update the placeholder

### ISSUE THREAD

**Issue by funniray** [Creeperface01/PlaceholderAPI-nukkit#1]
Basically, I have an event I listen for. The event updates the placeholder's value. I want to tell PlaceholderAPI that the placeholder just updated and with what value.

**Comment by Creeperface01** [comment]
you can use this method to check for placeholder update https://github.com/Creeperface01/PlaceholderAPI-nukkit/blob/master/src/main/kotlin/com/creeperface/nukkit/placeholderapi/api/PlaceholderAPI.kt#L73 however you can't choose it's value because it's got from the placeholder loader.

**Comment by funniray** [comment]
Yeah, I want to make it so a placeholder doesn't automatically update and I'm able to change the cached value. I would still let it grab the placeholder from the loader, but that would only be called on the forceupdate method.

**Comment by Creeperface01** [comment]
Why do you need that? You can create your own placeholder. Or your own placeholder class so you can do almost whatever you want.
