### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ghost** [Creeperface01/PlaceholderAPI-nukkit#13]
`[ERROR] Throwing                                                       
java.lang.RuntimeException: java.lang.NoSuchMethodError: 'com.creeperface.nukkit
.placeholderapi.api.scope.Scope com.creeperface.nukkit.placeholderapi.api.Placeh
older.getScope()`

PlaceHolder version 2.1
What should i do?

**Comment by Creeperface01** [comment]
Apparently certain plugin you didn't specify is using newer or older version version of PAPI, but it looks more like a newer
