### ISSUE TITLE
Support for ServerCommunicator

### ISSUE THREAD

**Issue by CallMeYuuuu** [Creeperface01/PlaceholderAPI-nukkit#6]
Hay, can you build in Server Communicator support to query and display other servers, eg usercount, or online status? Here you can find the plugin ServerCiommunicator:
[here](https://nukkitx.com/resources/servercommunicator.427/)
Thanks

**Comment by Creeperface01** [comment]
The purpose of PlaceholderAPI is to provide easily accessible interface for both users and developers. Simply it's a library that other plugins need to implement. (which isn't a problem imo). So ask the developer of that plugin to add PAPI support.
